name: CI/CD for Local Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-redeploy:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Redeploy Docker
      shell: powershell
      run: |
        # Tell PowerShell not to stop the script if a command fails
        $ErrorActionPreference = 'SilentlyContinue'
        
        docker stop python-server
        docker stop python-postgres-db
        docker rm python-server
        docker rm python-postgres-db
        
        # This is the only command that MUST succeed
        $ErrorActionPreference = 'Continue'
        docker-compose up -d --build