name: CI/CD for Local Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-redeploy:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Rebuild and Restart Docker Container
      # --remove-orphans ensures old containers from previous manual runs are cleared
      run: |
        docker-compose down --remove-orphans
        docker-compose up -d --build