name: CI/CD for Local Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-redeploy:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Windows Force Cleanup and Rebuild
      # We use PowerShell syntax to ignore errors if containers don't exist
      run: |
        docker stop python-server, python-postgres-db 2>$null
        docker rm -f python-server, python-postgres-db 2>$null
        docker-compose up -d --build